### ISSUE TITLE
Interested in extracting embeddings

### ISSUE THREAD

**Issue by snpushpi** [NUSTM/FacialMMT#10]
Hello all, 
Thanks for the great work. I was wondering if there is any way I could extract embeddings from the pre trained model for a given input? I was going through the code for train.py to see where I could find the part of extracting inputs, but it quickly became like a rabbit hole. Any pointers will be really appreciated. many thanks!

**Comment by wjzhengnlp** [comment]
I'm sorry, I didn't quite understand your question, feel free to email me.
