### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_lightning.lite'

### ISSUE THREAD

**Issue by yuandapiaoliang** [NUSTM/FacialMMT#3]
There is no lite file in pytorch_lighting
May I ask how to download this file？
![微信图片_20231017122354](https://github.com/NUSTM/FacialMMT/assets/115403620/ab2bf45e-c6d0-465e-8ab8-6448076b5fde)

**Comment by wjzhengnlp** [comment]
Thank you for your attention.
Your environment should satisfy all the libraries listed in requirements.txt.
