### ISSUE TITLE
No such file or directory: 'data/meld/preprocess_data/ref/update/train_text.json'

### ISSUE THREAD

**Issue by zyh9929** [NUSTM/FacialMMT#4]
No such file or directory: 'data/meld/preprocess_data/ref/update/train_text.json'

**Comment by wjzhengnlp** [comment]
Thank you for your attention. 
You need to obtain the text information of each utterance in MELD.

**Comment by wjzhengnlp** [comment]
We have also uploaded relevant files on the BaiduNetdisk.
