### ISSUE TITLE
Can you share preprocessing(stage 1) code?

### ISSUE THREAD

**Issue by ByeongjunCho** [NUSTM/FacialMMT#5]
Hi. Thanks to share code!

Do you have a plan to share preprocessing code(stage 1 part)? 
Because I want to try with my datasets. 
Want to know some of details at stage 1 part(threshold, face margin, ...)

Thank you

Best regards

Cho

**Comment by wjzhengnlp** [comment]
Thank you for your interest in our work. For your question, we are sorry that we have no public plan at the moment.

Best,
wenjie
