### ISSUE TITLE
UnboundLocalError: local variable 'tokenizer' referenced before assignment

### ISSUE THREAD

**Issue by Aminang** [NUSTM/FacialMMT#8]
Hey, execute the command python main.py --choice_modality T+A+V --plm_name roberta-large --load_multimodal_path FacialMMT-RoBERTa/multimodal_T+A+V_RoBERTa.pt --load_swin_path FacialMMT-RoBERTa/best_swin_RoBERTa.pt --doEval 1, the program returns error UnboundLocalError: local variable 'tokenizer' referenced before assignment, how to do it？

**Comment by wjzhengnlp** [comment]
please refer to issues https://github.com/NUSTM/FacialMMT/issues/6.

**Comment by Aminang** [comment]
> please refer to issues #6.
According to the proposed solution, it still can't solve the problem, the following is the error message after I executed the command, how to solve it？
load MELD_multimodal_T+A+V_train...
  - Creating new train data
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    trg_train_data = get_multimodal_data(args, 'train')
  File "E:\FacialMMT-main\utils\util.py", line 95, in get_multimodal_data
    data = loading_multimodal_data(args,split)
  File "FacialMMT-main\utils\dataset.py", line 303, in loading_multimodal_data
    meld_text_features = meld.preprocess_data()
  File "FacialMMT-main\src\meld_bert_extraText.py", line 89, in preprocess_data
    temp_utt.append(tokenizer.tokenize(utterance))
UnboundLocalError: local variable 'tokenizer' referenced before assignment

**Comment by wjzhengnlp** [comment]
environment setup issue?

**Comment by Aminang** [comment]
> 环境设置问题？
Environments are configured according to requirements
<img width="432" alt="1" src="https://github.com/NUSTM/FacialMMT/assets/58494368/b6ef3b72-6bc4-4fd9-962e-597117c2a552">
<img width="424" alt="7" src="https://github.com/NUSTM/FacialMMT/assets/58494368/bff4a4f2-12a5-47e8-81da-524327fb164c">

**Comment by wjzhengnlp** [comment]
https://github.com/NUSTM/FacialMMT/blob/main/src/meld_bert_extraText.py#L69

<img width="627" alt="image" src="https://github.com/NUSTM/FacialMMT/assets/53817049/afc1d169-2d70-4d67-8366-10f864bec17b">

Is the path of the pre-trained model loaded correct?

**Comment by Aminang** [comment]
> https://github.com/NUSTM/FacialMMT/blob/main/src/meld_bert_extraText.py#L69
> 
> <img alt="图像" width="627" src="https://private-user-images.githubusercontent.com/53817049/313897810-afc1d169-2d70-4d67-8366-10f864bec17b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTcyNTksIm5iZiI6MTcxMDgxNjk1OSwicGF0aCI6Ii81MzgxNzA0OS8zMTM4OTc4MTAtYWZjMWQxNjktMmQ3MC00ZDY3LTgzNjYtMTBmODY0YmVjMTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAyNTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNDVmYmJhNzE0NzYwZjU3YmE5MjU1MmZjYWJhMzFkMmI4NDc3MTQ3OGVlZjMwN2Q2MTU3YWFjNGIxODhmZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BUyYQEgxfxGxV5wpOqxveYqDBRiy1enBBjV1l7JmGB8">
> 加载的预训练模型的路径是否正确？
The issue has been fixed after the change, but a new problem has appeared, and the following is the error message
<img width="987" alt="微信截图_20240319162847" src="https://github.com/NUSTM/FacialMMT/assets/58494368/3f6cf559-5572-4bef-ad3c-40b980db7482">

**Comment by wjzhengnlp** [comment]
It feels like the data isn't loading properly.

**Comment by wjzhengnlp** [comment]
Check again that the path to the data entry is correct.

**Comment by Aminang** [comment]
> Check again that the path to the data entry is correct.

Hello, I printed text_utt_linear output dimension, as well as curr_dia_mask and batchUtt_in_dia_idx, and when traversing the curr_dia_mask later, because the value=1 condition is satisfied, the curr_utt_in_dia_idx==0 is executed, so the program executes curr_utt_len = index-1, which is curr_utt_len The end is equal to -1, so at the end there was an error in text_utt_linear[i][1:curr_utt_len+1], and here is the output
<img width="766" alt="微信截图_20240320225851" src="https://github.com/NUSTM/FacialMMT/assets/58494368/7353160e-0d66-4c00-935b-7911ab018a14">

**Comment by wjzhengnlp** [comment]
<img width="275" alt="image" src="https://github.com/NUSTM/FacialMMT/assets/53817049/c253c462-6a7b-4b1a-86f7-bcb14ba97f28">

https://github.com/NUSTM/FacialMMT/blob/main/src/models.py#L107

the number of dialogue is 2?

**Comment by Aminang** [comment]
> <img alt="image" width="275" src="https://private-user-images.githubusercontent.com/53817049/314905477-c253c462-6a7b-4b1a-86f7-bcb14ba97f28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODg5MDIsIm5iZiI6MTcxMDk4ODYwMiwicGF0aCI6Ii81MzgxNzA0OS8zMTQ5MDU0NzctYzI1M2M0NjItNmE3Yi00YjFhLTg2ZjctYmNiMTRiYTk3ZjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAyMzY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZmE1MmEwNTZhZTcyZDA4NzM1YjJhZjgzOGIzOWFjOTcyYWYyMWY5ZjVmMTE2NzViZWMzY2FmNWFlNzQ3ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5E48Zn6XbBYzLD9PVJrCL7x3i-arTiDudXEqXhdFi0c">
> https://github.com/NUSTM/FacialMMT/blob/main/src/models.py#L107
> 
> the number of dialogue is 2?

When batch_size=1, the above problem also exists.

**Comment by wjzhengnlp** [comment]
I don't seem to be very clear about it either. 

I can ensure that the code, data, and models I upload are correctly loaded and yield the corresponding results. 

So, you can check each line in debug mode. Before that, please make sure paths of all model loading and data loading are correct. 

If you have any further questions, we can continue discussion. The issue#8 will remain open.
